### PR TITLE
Update class-lazy-load.php

### PR DESCRIPTION
**Pull request by Adam-EWWW**
Finally found the right one!  From the testing that I've done, this moves the noscript to outside of the picture element.

### CODE REVIEW

**Comment by nosilver4u** [comment]
If I'm looking at it right though, it'll put in the altered (lazified) img inside the noscript though--because str_replace() should replace all occurrences of the original img tag, not just the first one, and the noscript img should be identical to the original.
If that is indeed the case, I believe you could append the noscript outside/after str_replace() to make sure the noscript img  isn't altered.

**Comment by Adam-EWWW** [comment]
Ahhh blarg.  Yup.  I moved it.

**Comment by nosilver4u** [comment]
Yup, just like that! Except, there's a missing space that made Travis fall over :)

**Review by nosilver4u — APPROVED** [review]

**Comment by nosilver4u** [comment]
Go ahead and merge it!

**Pull request merged**
